[build]
  command = "node scripts/set-env.js && npm run build"
  publish = "dist/back-to-school-bash/browser"

[build.environment]
  NETLIFY_SKIP_ANGULAR_PLUGIN = "true"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
